// src/pages/limits/limits.page.vue
<script setup lang="ts">
import { DownloadLimits, UploadLimits } from '@/features/limits'
import { Modal, ModalContent } from '@/shared/ui'
</script>

<template>
  <Modal>
    <ModalContent title="Limits">
      <DownloadLimits />

      <div class="mt-8">
        <UploadLimits />
      </div>
    </ModalContent>
  </Modal>
</template>

// src/pages/limits/limits.page.svelte
<script lang="ts">
  import { t } from 'shared/i18n'
  import { ModalContent } from 'shared/ui'
  import { DownloadLimits, UploadLimits } from 'features/limits'
</script>

<ModalContent title={$t('stats.limits')}>
  <DownloadLimits />

  <div class="mt-8">
    <UploadLimits />
  </div>
</ModalContent>
