// src/entities/torrents/ui/torrent-item.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { Card } from '@/shared/ui'
import { type Torrent } from '../model'
import {
  TorrentInfoCompleted,
  TorrentInfoDownloading,
  TorrentInfoError,
  TorrentInfoOther,
  TorrentInfoPaused,
} from './torrent-info'

const props = defineProps<{ torrent: Torrent }>()
</script>

<template>
  <RouterLink class="not-link" :to="`/torrent/${props.torrent.id}`">
    <Card>
      <div class="content flex flex-col gap-2">
        <h3 class="break-words">{{ props.torrent.name }}</h3>

        <TorrentInfoCompleted v-if="props.torrent.progress >= 1" :torrent="props.torrent" />
        <TorrentInfoDownloading v-else-if="props.torrent.state === 'downloading'" :torrent="props.torrent" />
        <TorrentInfoPaused v-else-if="props.torrent.state === 'pausedDL'" :torrent="props.torrent" />
        <TorrentInfoError v-else-if="props.torrent.state === 'missingFiles'" :torrent="props.torrent" />
        <TorrentInfoOther v-else :torrent="props.torrent" />
      </div>
    </Card>
  </RouterLink>
</template>

<style scoped>
h3 {
  font-size: 20px;
  font-weight: bold;
}

@screen lt-sm {
  h3 {
    font-size: 14px;
  }

  .content {
    font-size: 12px;
  }
}
</style>

// src/entities/torrents/ui/torrent-item.svelte
<script lang="ts">
import { Card } from 'shared/ui'
import { Link } from 'svelte-routing'
import { type Torrent } from '../model'
import {
  TorrentInfoCompleted,
  TorrentInfoDownloading,
  TorrentInfoError,
  TorrentInfoOther,
  TorrentInfoPaused,
} from './torrent-info'

export let torrent: Torrent
</script>

<Link class="not-link" to={`torrent/${torrent.id}`}>
  <Card>
    <div class="content flex flex-col gap-2">
      <h3 class="break-words">{torrent.name}</h3>

      {#if torrent.progress >= 1}
        <TorrentInfoCompleted {torrent} />
      {:else if torrent.state === 'downloading'}
        <TorrentInfoDownloading {torrent} />
      {:else if torrent.state === 'pausedDL'}
        <TorrentInfoPaused {torrent} />
      {:else if torrent.state === 'missingFiles'}
        <TorrentInfoError {torrent} />
      {:else}
        <TorrentInfoOther {torrent} />
      {/if}
    </div>
  </Card>
</Link>

<style>
  h3 {
    font-size: 20px;
    font-weight: bold;
  }

  /* Mobile */
  :global(#mobile) h3 {
    font-size: 14px;
  }

  :global(#mobile) .content {
    font-size: 12px;
  }
</style>
