// src/shared/ui/modal-button.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import Icon from './icon.vue'

defineProps<{ icon: string; title: string; to: string }>()
</script>

<template>
  <RouterLink class="nav-link not-link flex flex-col items-center justify-center" :to="to" :replace="true">
    <Icon :icon="icon" />
    <div>{{ title }}</div>
  </RouterLink>
</template>

// src/shared/ui/modal-button.svelte
<script lang="ts">
  import { Link } from 'svelte-routing'
  import Icon from './icon.svelte'

  export let icon: string
  export let title: string
  export let to: string
</script>

<Link class="nav-link not-link flex flex-col items-center justify-center" {to}>
  <Icon {icon} />
  <div>{title}</div>
</Link>
