// src/pages/add/add.page.vue
<script setup lang="ts">
import { categories, guessCategory } from 'entities/torrents'
import { api } from 'shared/api'
import { FileSelect, Modal, ModalContent } from 'shared/ui'
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'

const files = ref<FileList | null>(null)
const category = ref('')
const sequentialDownload = ref(true)

const disabled = computed(() => !files.value?.length)

watch(files, (newFiles) => {
  const filename = newFiles?.[0]?.name

  if (filename) {
    category.value = guessCategory(filename)
  }
})

const router = useRouter()

const submit = async () => {
  if (files.value?.length) {
    for (const file of [...files.value]) {
      const result = await api.torrent.add(file, category.value, sequentialDownload.value)

      if (!result) {
        return alert(`Error on file ${file.name}!`)
      }
    }

    router.replace('/')
  }
}
</script>

<template>
  <Modal>
    <ModalContent title="Add a torrent">
      <form class="flex flex-col gap-4" @submit.prevent="submit">
        <FileSelect v-model:files="files" accept=".torrent" autoselect multiple />

        <h2>Category</h2>

        <label> <input :checked="!category" type="radio" name="category" value="" @change="category = ''"> None </label>

        <label v-for="cat in categories" :key="cat.id">
          <input
            :checked="category === cat.id"
            type="radio"
            name="category"
            :value="cat.id"
            @change="category = cat.id"
          >
          {{ cat.name }}
        </label>

        <label>
          <input v-model="sequentialDownload" type="checkbox">
          Sequential Download
        </label>

        <button :disabled="disabled">Send</button>
      </form>
    </ModalContent>
  </Modal>
</template>

// src/pages/add/add.page.svelte
<script lang="ts">
  import { categories, guessCategory } from 'entities/torrents'
  import { api } from 'shared/api'
  import { FileSelect, ModalContent } from 'shared/ui'
  import { navigate } from 'svelte-routing'

  let files: FileList | null
  let category = ''
  let sequentialDownload = true

  $: disabled = !files?.length
  $: {
    const filename = files?.[0].name

    if (filename) {
      category = guessCategory(filename)
    }
  }

  const submit = async () => {
    if (files?.length) {
      for (const file of [...files]) {
        const result = await api.torrent.add(file, category, sequentialDownload)

        if (!result) {
          return alert(`Error on file ${file.name}!`)
        }
      }

      navigate('/')
    }
  }
</script>

<ModalContent title="Add a torrent">
  <form class="flex flex-col gap-4" on:submit|preventDefault={submit}>
    <FileSelect bind:files accept=".torrent" autoselect multiple />

    <h2>Category</h2>

    <label>
      <input checked={!category} on:change={() => (category = '')} type="radio" name="category" value="" /> None
    </label>

    {#each $categories as cat (cat.id)}
      <label>
        <input
          checked={category === cat.id}
          on:change={() => (category = cat.id)}
          type="radio"
          name="category"
          value={cat.id}
        />
        {cat.name}
      </label>
    {/each}

    <label>
      <input type="checkbox" bind:checked={sequentialDownload} />
      Sequential Download
    </label>

    <button {disabled}>Send</button>
  </form>
</ModalContent>
