// src/features/limits/ui/limits-block.vue
<script setup lang="ts">
import { formatBytes } from 'shared/lib/format'
import { Icon } from 'shared/ui'

const props = defineProps<{ icon: string; limit: number }>()
const emit = defineEmits<{ limitChange: [limit: number] }>()

const limits = [1, 2, 3, 5, 8, 10, 15].map((limit) => limit * 1024 * 1024)
</script>

<template>
  <div class="flex gap-2">
    <Icon :icon="props.icon" />
    <h1>{{ formatBytes(props.limit) }}</h1>
  </div>

  <div class="mt-2 flex flex-wrap gap-2">
    <button
      v-for="limitMb in limits"
      :key="limitMb"
      :class="{ secondary: props.limit !== limitMb }"
      @click="emit('limitChange', limitMb)"
    >
      {{ formatBytes(limitMb) }}
    </button>
  </div>
</template>

// src/features/limits/ui/limits-block.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte'
  import { formatBytes } from 'shared/lib/format'
  import { Icon } from 'shared/ui'

  export let icon: string
  export let limit: number

  const limits = [1, 2, 3, 5, 8, 10].map((limitB) => limitB * 1024 * 1024)

  const dispatch = createEventDispatcher<{ limitChange: number }>()
</script>

<div class="flex gap-2">
  <Icon {icon} />
  <h1>{formatBytes(limit)}</h1>
</div>

<div class="mt-2 flex flex-wrap gap-2">
  {#each limits as limitMb}
    <button class:secondary={limit !== limitMb} on:click={() => dispatch('limitChange', limitMb)}>
      {formatBytes(limitMb)}</button
    >
  {/each}
</div>
