// src/features/limits/ui/upload-limits.vue
<script setup lang="ts">
import { maindata } from '@/entities/stats'
import { icons } from '@/shared/ui'
import { setUploadLimit } from '../model'
import LimitsBlock from './limits-block.vue'
</script>

<template>
  <LimitsBlock
    :icon="icons.arrowUp"
    :limit="maindata?.server_state.up_rate_limit ?? 0"
    @limit-change="setUploadLimit"
  />
</template>

// src/features/limits/ui/upload-limits.svelte
<script lang="ts">
  import { icons } from 'shared/ui'
  import { maindata } from 'entities/stats'
  import { setUploadLimit } from '../model'
  import LimitsBlock from './limits-block.svelte'
</script>

<LimitsBlock
  icon={icons.arrowUp}
  limit={$maindata?.server_state.up_rate_limit ?? 0}
  on:limitChange={(event) => setUploadLimit(event.detail)}
/>
